# Generated by Django 4.2.4 on 2023-09-03 03:38

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('heading', wagtail.blocks.CharBlock(form_classname='heading')), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True),
        ),
    ]
