# Generated by Django 4.2.4 on 2023-09-03 04:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postpage_excerpt_alter_postpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock(icon='h1', label='Heading 1')), ('h2', wagtail.blocks.CharBlock(icon='h2', label='Heading 2')), ('h3', wagtail.blocks.CharBlock(icon='h3', label='Heading 3')), ('paragraph', wagtail.blocks.RichTextBlock(icon='draft')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))], use_json_field=True),
        ),
    ]
